(() => {
'use strict';
const $=s=>document.querySelector(s),root=$('#game-root'),canvas=$('#arena'),ctx=canvas.getContext('2d'),overlay=$('#overlay');
const W=1200,H=700,CYAN='#67f8ea',CORAL='#ff697b',keys=new Set();
let muted=false,audio=null,audioEvents=0;
let state='title',player, enemies=[],bullets=[],particles=[],trails=[],shots=0,kills=0,dashes=0,dashKills=0,trailHits=0,score=0,wave=1,last=0,time=0,shake=0,shotTimer=0,enemyShots=[],banner=0,mouse={x:900,y:350,down:false},seed=73;
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function resetPlayer(){player={x:600,y:350,hp:100,maxHp:100,speed:260,damage:20,fireRate:.16,dash:0,cooldown:0,invuln:0,angle:0,dx:1,dy:0};}
resetPlayer();
function sync(){Object.assign(root.dataset,{state,muted,audioEvents,shotsFired:shots,enemyCount:enemies.length,kills,dashes,dashKills,trailHits,wave,score,health:Math.ceil(player.hp)});$('#health').textContent=Math.ceil(player.hp);$('#health-bar').style.width=`${player.hp/player.maxHp*100}%`;$('#wave').textContent=String(wave).padStart(2,'0');$('#score').textContent=String(score).padStart(6,'0');$('#status').textContent=state==='playing'?'SIGNAL LIVE / '+enemies.length+' HOSTILES':state.toUpperCase();$('#dash-status').textContent=player.cooldown>0?`PHASE DRIVE / ${player.cooldown.toFixed(1)}s`:'PHASE DRIVE / READY';}
function spawn(x,y,type='chaser'){const e={x,y,type,hp:30,r:15,speed:75,age:0};enemies.push(e);return e;}
function beginWave(){
 enemies=[];bullets=[];enemyShots=[];player.x=600;player.y=350;player.invuln=1.5;banner=2.5;$('#announcement').textContent=wave%3===0?'WARNING // THE GATEKEEPER':'WAVE '+String(wave).padStart(2,'0')+' // BREACH DETECTED';
 if(wave%3===0){const e=spawn(600,130,'boss');Object.assign(e,{hp:500+wave*70,maxHp:500+wave*70,r:47,speed:32,timer:1.5});}
 else for(let i=0;i<Math.min(24,5+wave*2);i++){let a=i/(5+wave*2)*Math.PI*2;const e=spawn(600+Math.cos(a)*470,350+Math.sin(a)*270,i%3===1?'shooter':'chaser');e.speed=65+wave*9;e.hp=26+wave*5;e.timer=1.5+i*.25;}
}
function finishWave(){if(state!=='playing')return;state='upgrade';enemyShots=[];bullets=[];player.hp=Math.min(player.maxHp,player.hp+20);overlay.hidden=false;$('#announcement').textContent='';overlay.innerHTML=`<p class="eyebrow">SIGNAL SECURED / WAVE ${String(wave).padStart(2,'0')}</p><h2>${wave%3===0?'CORE SHATTERED':'REWIRE. RELOAD. REPEAT.'}</h2><p class="intro">+20 hull repaired. Choose one permanent augmentation.</p><div class="upgrades"><button class="upgrade" data-upgrade="rate"><strong>01 / Overclock</strong><span>Fire 20% faster.<br>Make every second count.</span></button><button class="upgrade" data-upgrade="hull"><strong>02 / Reinforced</strong><span>+25 maximum hull.<br>Repair to full integrity.</span></button><button class="upgrade" data-upgrade="power"><strong>03 / Hot rounds</strong><span>+10 weapon damage.<br>Turn pressure into power.</span></button></div><p class="instructions">THE BREACH DEEPENS. A GATEKEEPER ARRIVES EVERY THIRD WAVE.</p>`;overlay.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{if(b.dataset.upgrade==='rate')player.fireRate=Math.max(.055,player.fireRate*.8);if(b.dataset.upgrade==='hull'){player.maxHp+=25;player.hp=player.maxHp;}if(b.dataset.upgrade==='power')player.damage+=10;wave++;state='playing';overlay.hidden=true;beginWave();sync();});sync();}
function start(){initAudio();keys.clear();mouse.down=false;resetPlayer();enemies=[];bullets=[];particles=[];trails=[];shots=kills=dashes=dashKills=trailHits=score=0;wave=1;shotTimer=0;seed=73;state='playing';overlay.hidden=true;beginWave();sync();}
function initAudio(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{audio=null;}}
function sound(freq,duration=.08,type='triangle',end=80){if(muted||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(end,audio.currentTime+duration);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);audioEvents++;}catch{}}
function toggleMute(){muted=!muted;$('#mute').textContent=muted?'M · SOUND OFF':'M · SOUND ON';$('#mute').setAttribute('aria-label',muted?'Unmute audio':'Mute audio');sync();}
function pause(){if(state==='playing'){state='paused';keys.clear();mouse.down=false;overlay.hidden=false;overlay.innerHTML='<p class="eyebrow">SIGNAL HELD</p><h2>TAKE A BREATH.</h2><p class="intro">The breach can wait.</p><button class="primary" id="resume">Resume run ↗</button>';$('#resume').onclick=pause;}else if(state==='paused'){state='playing';overlay.hidden=true;keys.clear();}sync();}
function hurt(damage){if(state!=='playing'||player.invuln>0)return;player.hp=Math.max(0,player.hp-damage);player.invuln=.8;shake=12;burst(player.x,player.y,CORAL,25);sound(110,.2,'sawtooth',35);if(!player.hp){state='gameover';keys.clear();mouse.down=false;overlay.hidden=false;$('#announcement').textContent='';overlay.innerHTML=`<p class="eyebrow">CONNECTION LOST / WAVE ${wave}</p><h2>NOT YOUR LAST RUN.</h2><p class="intro">${String(score).padStart(6,'0')} sync score · ${kills} hostiles erased<br>The rift remembers. Go again.</p><button class="primary" id="restart">Restart run ↗</button>`;$('#restart').onclick=start;}sync();}
function burst(x,y,color,n=16){for(let i=0;i<n;i++){let a=rand()*Math.PI*2,v=40+rand()*210;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.3+rand()*.5,max:.8,color});}if(particles.length>550)particles.splice(0,particles.length-550);}
function hit(e,damage,dash=false){if(e.hp<=0)return;e.hp-=damage;burst(e.x,e.y,dash?CYAN:CORAL,5);if(e.hp<=0){kills++;score+=e.type==='boss'?2500:100;sound(e.type==='boss'?65:160,.14,'sawtooth',40);if(dash)dashKills++;burst(e.x,e.y,CORAL,22);shake=4;}}
function dash(){if(state!=='playing'||player.cooldown>0)return;let x=+(keys.has('d')||keys.has('arrowright'))-+(keys.has('a')||keys.has('arrowleft')),y=+(keys.has('s')||keys.has('arrowdown'))-+(keys.has('w')||keys.has('arrowup'));let n=Math.hypot(x,y);player.dx=n?x/n:Math.cos(player.angle);player.dy=n?y/n:Math.sin(player.angle);player.dash=.2;player.cooldown=2.2;player.invuln=.3;dashes++;sound(180,.25,'sawtooth',650);burst(player.x,player.y,CYAN);}
function shoot(){let a=player.angle;if(keys.has('f')&&enemies.length){let target=enemies.reduce((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)<Math.hypot(b.x-player.x,b.y-player.y)?a:b);a=Math.atan2(target.y-player.y,target.x-player.x);player.angle=a;}bullets.push({x:player.x+Math.cos(a)*20,y:player.y+Math.sin(a)*20,vx:Math.cos(a)*800,vy:Math.sin(a)*800,life:1.6});shots++;sound(640,.065,'triangle',180);burst(player.x+Math.cos(a)*21,player.y+Math.sin(a)*21,CYAN,2);}
function phaseHit(e,id,trail=false){if(e.lastDash===id)return;e.lastDash=id;if(trail)trailHits++;hit(e,100,true);}
function update(dt){time+=dt;banner-=dt;if(banner<=0)$('#announcement').textContent='';player.cooldown=Math.max(0,player.cooldown-dt);player.invuln=Math.max(0,player.invuln-dt);shotTimer-=dt;let x=+(keys.has('d')||keys.has('arrowright'))-+(keys.has('a')||keys.has('arrowleft')),y=+(keys.has('s')||keys.has('arrowdown'))-+(keys.has('w')||keys.has('arrowup'));const n=Math.hypot(x,y);player.angle=Math.atan2(mouse.y-player.y,mouse.x-player.x);if(player.dash>0){player.dash-=dt;player.x+=player.dx*1000*dt;player.y+=player.dy*1000*dt;trails.push({x:player.x,y:player.y,angle:player.angle,life:.4,id:dashes});}else if(n){player.x+=x/n*player.speed*dt;player.y+=y/n*player.speed*dt;}player.x=clamp(player.x,30,W-30);player.y=clamp(player.y,30,H-30);if((keys.has('f')||mouse.down)&&shotTimer<=0){shoot();shotTimer=player.fireRate;}for(const e of enemies){e.age+=dt;let a=Math.atan2(player.y-e.y,player.x-e.x);let dist=Math.hypot(player.x-e.x,player.y-e.y);if(e.type!=='shooter'||dist>270){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt;}if(e.type==='boss'||e.type==='shooter'){e.timer-=dt;if(e.timer<=0){let count=e.type==='boss'?14:1;for(let j=0;j<count;j++){let angle=count===1?a:j/count*Math.PI*2+e.age*.2;enemyShots.push({x:e.x,y:e.y,vx:Math.cos(angle)*180,vy:Math.sin(angle)*180,life:6});}e.timer=e.type==='boss'?1.6:2.7;}}if(player.dash>0&&Math.hypot(e.x-player.x,e.y-player.y)<e.r+26)phaseHit(e,dashes);else if(e.hp>0&&Math.hypot(e.x-player.x,e.y-player.y)<e.r+13)hurt(e.type==='boss'?30:18);}for(const t of trails){t.life-=dt;if(t.life>0)for(const e of enemies)if(e.hp>0&&Math.hypot(t.x-e.x,t.y-e.y)<e.r+19)phaseHit(e,t.id,true);}trails=trails.filter(t=>t.life>0);for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of enemies)if(e.hp>0&&Math.hypot(e.x-b.x,e.y-b.y)<e.r+5){hit(e,player.damage);b.life=0;break;}}bullets=bullets.filter(b=>b.life>0);enemies=enemies.filter(e=>e.hp>0);for(const b of enemyShots){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(Math.hypot(b.x-player.x,b.y-player.y)<18){hurt(14);b.life=0;}}enemyShots=enemyShots.filter(b=>b.life>0);if(!enemies.length)finishWave();sync();}
function polygon(x,y,r,sides,angle,color,fill='#152b38'){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.beginPath();for(let i=0;i<sides;i++){let a=i/sides*Math.PI*2;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r);}ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=12;ctx.stroke();ctx.restore();}
function draw(dt){ctx.fillStyle='#07111f';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate((rand()-.5)*shake,(rand()-.5)*shake);shake=Math.max(0,shake-dt*25);ctx.strokeStyle='#112a3a';ctx.lineWidth=1;for(let x=0;x<W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke();}for(let y=0;y<H;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}ctx.strokeStyle='#235061';ctx.strokeRect(20,20,W-40,H-40);ctx.setLineDash([4,10]);ctx.beginPath();ctx.arc(600,350,180,0,7);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#173345';ctx.beginPath();ctx.arc(600,350,240,0,7);ctx.stroke();ctx.fillStyle='#163545';ctx.font='10px monospace';ctx.textAlign='center';ctx.fillText('R I F T   C O N T A I N M E N T   Z O N E',600,620);for(const [x,y]of [[50,50],[1150,50],[50,650],[1150,650]]){polygon(x,y,10,4,time*.15,CYAN);ctx.fillStyle='#30576b';ctx.fillRect(x-2,y-25,4,8);ctx.fillRect(x-2,y+18,4,8);}for(const t of trails){ctx.globalAlpha=Math.max(0,t.life/.4)*.5;polygon(t.x,t.y,17,3,t.angle,CYAN);}ctx.globalAlpha=1;trails=trails.filter(t=>t.life>0);for(const e of enemies){polygon(e.x,e.y,e.r,e.type==='boss'?6:e.type==='shooter'?3:4,e.age*.8,e.type==='shooter'?'#ffbd7a':CORAL);if(e.type==='boss'){polygon(e.x,e.y,e.r+12,6,-e.age*.6,CORAL);ctx.fillStyle='#3b2436';ctx.fillRect(400,55,400,6);ctx.fillStyle=CORAL;ctx.fillRect(400,55,400*e.hp/e.maxHp,6);ctx.font='11px monospace';ctx.fillText('THE GATEKEEPER // '+Math.ceil(e.hp),600,45);}ctx.fillStyle=CORAL;ctx.fillRect(e.x-3,e.y-3,6,6);}for(const b of enemyShots){ctx.fillStyle=CORAL;ctx.shadowColor=CORAL;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(b.x,b.y,5,0,7);ctx.fill();}ctx.shadowColor=CYAN;ctx.shadowBlur=14;ctx.strokeStyle=CYAN;ctx.lineWidth=3;for(const b of bullets){ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.018,b.y-b.vy*.018);ctx.stroke();}ctx.shadowBlur=0;for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);}ctx.globalAlpha=1;particles=particles.filter(p=>p.life>0);if(player.invuln<=0||Math.sin(time*60)>0)polygon(player.x,player.y,18,3,player.angle,CYAN,'#123845');ctx.beginPath();ctx.arc(player.x,player.y,26,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-player.cooldown/2.2));ctx.strokeStyle='#67f8ea50';ctx.lineWidth=2;ctx.stroke();ctx.restore();}
function frame(now){let dt=Math.min((now-last)/1000,.033);last=now;if(state==='playing')update(dt);draw(dt);requestAnimationFrame(frame);}
$('#start').onclick=start;addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key===' '&&!e.repeat)dash();if(e.key.toLowerCase()==='p'&&!e.repeat)pause();if(e.key.toLowerCase()==='m'&&!e.repeat)toggleMute();});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('pointermove',e=>{let r=canvas.getBoundingClientRect();if(getComputedStyle(canvas).objectFit==='contain'){const scale=Math.min(r.width/W,r.height/H);mouse.x=(e.clientX-r.left-(r.width-W*scale)/2)/scale;mouse.y=(e.clientY-r.top-(r.height-H*scale)/2)/scale;}else{mouse.x=(e.clientX-r.left)/r.width*W;mouse.y=(e.clientY-r.top)/r.height*H;}});canvas.addEventListener('pointerdown',()=>mouse.down=true);addEventListener('pointerup',()=>mouse.down=false);
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch{}keys.add(b.dataset.key);if(b.dataset.key===' ')dash();});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(b.dataset.key));});
$('#pause').onclick=pause;$('#mute').onclick=toggleMute;addEventListener('blur',()=>{keys.clear();mouse.down=false;if(state==='playing')pause();});
window.__gameTest={snapshot:()=>({state,mouse:{...mouse},player:{...player},shots,kills,dashes,dashKills,trailHits,wave,score,muted,audioEvents,enemies:enemies.map(e=>({...e}))}),clearWave(){for(const e of enemies)hit(e,99999);enemies=[];finishWave();},setupBossShot(){const e=enemies.find(e=>e.type==='boss');player.x=e.x;player.y=e.y+150;player.invuln=5;},probeAfterimage(){enemies=[];bullets=[];enemyShots=[];trails=[];keys.clear();player.x=600;player.y=350;player.angle=0;player.cooldown=0;spawn(50,50).speed=0;dash();for(let i=0;i<14;i++)update(1/60);const t=trails[trails.length-3],e=spawn(t.x,t.y);e.hp=300;e.speed=0;const before=e.hp;update(1/60);const after=e.hp;update(1/60);return{damage:before-after,repeatDamage:after-e.hp,trailHits};},setupLethalCollision(){player.hp=1;player.invuln=0;enemies=[];spawn(player.x,player.y);},setupCombat(mode){state='playing';overlay.hidden=true;player.x=600;player.y=350;player.cooldown=0;enemies=[];bullets=[];const e=spawn(mode==='dash'?680:750,350);e.speed=0;spawn(80,80).speed=0;}};sync();requestAnimationFrame(frame);
})();